package pages.locators;

public enum ElementKey {
   AUDIO_CALL_BUTTON,
    FIRST_Search_RESULT,
    MOREOPTION,
    SEARCHBAR_Field,
    SEARCHBAR,
    ACCEPT_CALL_BUTTON,
 CALL_BUTTON,
 ALLOW_BUTTON,
    CALL_TIMER,
    CALL_STATUS_TEXT,
    VIDEO_UPGRADE_BUTTON,
    REMOTE_VIDEO_CONTAINER,
    ANSWER_VIDEO,
    HANG_UP_BUTTON,
    REJECT_CALL_BUTTON,
    VIDEO_CALL_BUTTON,
    EMAIL_FIELD,
    PASSWORD_FIELD,
 QUALITY_SIGN,
    LOGIN_SUBMIT_BUTTON,
    CONTINUE_BUTTON,
 ALLOW_ACCESS_CAMERA,
    ADD_PARTICIPANTS_BUTTON,
    CALL_PARTICIPANT_OPTION_BUTTON
}